In [1]:
#Consider the below code to answer further questions:
import numpy as np

In [2]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

In [6]:
type(array_list[0])

numpy.str_

In [7]:
'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans - 
    Yes there is difference between variables list_ and array_list.
    Variable list_ have list datatype on the other hand array_list is of numpy.ndarray datatype.'''

print(type(list_))

print(type(array_list))



<class 'list'>
<class 'numpy.ndarray'>


In [8]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.'''

for i,j in zip(list_, array_list):
    print(f"Data type of element '{i}' in list_ is {type(i)} and  Data type of element '{j}' in array_list is {type(j)}\n")

Data type of element '1' in list_ is <class 'str'> and  Data type of element '1' in array_list is <class 'numpy.str_'>

Data type of element '2' in list_ is <class 'str'> and  Data type of element '2' in array_list is <class 'numpy.str_'>

Data type of element '3' in list_ is <class 'str'> and  Data type of element '3' in array_list is <class 'numpy.str_'>

Data type of element '4' in list_ is <class 'str'> and  Data type of element '4' in array_list is <class 'numpy.str_'>

Data type of element '5' in list_ is <class 'str'> and  Data type of element '5' in array_list is <class 'numpy.str_'>



In [9]:
'''Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? 
If so then print the data types of each and every element present in both the variables, list_ and array_list.
'''
array_list = np.array(object = list_, dtype = int)

In [10]:
array_list[0]

1

In [11]:
type(array_list[0])

numpy.int32

# Ans

## Yes there will be difference between the elements in variables list_ and array_list considering the above changes. Elements in variable list_ have "str" datatype on the other hand elements in modified variable array_list is of "numpy.int32" datatype.

In [12]:
for i,j in zip(list_, array_list):
    print(f"Data type of element '{i}' in list_ is {type(i)} and  Data type of element '{j}' in array_list is {type(j)}\n")

Data type of element '1' in list_ is <class 'str'> and  Data type of element '1' in array_list is <class 'numpy.int32'>

Data type of element '2' in list_ is <class 'str'> and  Data type of element '2' in array_list is <class 'numpy.int32'>

Data type of element '3' in list_ is <class 'str'> and  Data type of element '3' in array_list is <class 'numpy.int32'>

Data type of element '4' in list_ is <class 'str'> and  Data type of element '4' in array_list is <class 'numpy.int32'>

Data type of element '5' in list_ is <class 'str'> and  Data type of element '5' in array_list is <class 'numpy.int32'>



In [13]:
#Consider the below code to answer further questions:

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
'''Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size'''

num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# (i) shape

num_array.shape

(2, 3)

In [16]:
# (ii) size

num_array.size

6

In [17]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]'''

'Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.\n[Hint: The size of the array will be 9 and the shape will be (3,3).]'

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]'''

np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])